# Project language
language: php
sudo: false

# PHP version
php:
  - 8.1

# Cache composer packages so "composer install" is faster
cache:
  directories:
    - ${HOME}/.composer/cache/files

addons:
  sonarcloud:
    organization: "adshares-github"
    token:
      secure: "CrUof1+C1uYYH+3m4Je6tOyGge5qB8GPRNBH8T3doIrjLuXhs74ah+9qT9jgOwfDH9Rb6661oTIQVxuWjg5mJIDBnc8TnV0lROo4fVKYMc9F/YyPbYqYRz8Jyyup2s1xvgbGG43ho8tPY2tq7Dzwr0NUVYumWGOwdIejnSZkFGD6Hg6S1bkRq+MbUtXtLEcSjaH8wvhKDJNObK2xo3/v98XEE+kLLB4/R4QGaSCvZlQRgkZy+kMZ6ihnPKbR1faYDOe/rOZMmcsIMK0J32ujS2Y+ky/psYsrjIkZwXdIjObg8VCeBokfp/t9NpKuMPzffofG+eyHzvuo+V+M6Nt7blt2BrMsoBk8eQjv1UnYuPoiBnC3cQ09OMWeg6BQpwFMbU8XJSrvA9Qt2gMK/pkld7DsjV0ZOaBGrMpeU/JCD5Px6GAz14pIxAe/+Bz79Dvt/6y/RYvDtiP9x9Zn5PXrGCYbdILJ13mBnSI2oO9PI7osicaRL3dOaOSI/ID3+8jqu8wfB3Z4acnh06vttMNuTPF285PLJaFy2sGaxd+fUW4zYjWrOSoJbFnd6/2aQwBuk3Gu7/Vu5lGs132z3IB0IfqzHB/yDoHngNWezxdz0tJh/lZn1IoJ0ptXfJFuOy9buRACNEZ8YwA3L6d6QE8pBMcfq+ChdJk76w3jWO9mXsw="

# Install composer dependencies
install:
  - composer install --no-ansi --no-scripts --no-interaction --no-progress --no-suggest
  - mkdir var

script:
  # SensioLabs Security Checker: checks security issues
  - wget -c https://github.com/fabpot/local-php-security-checker/releases/download/v1.0.0/local-php-security-checker_1.0.0_linux_amd64 -O local-php-security-checker && chmod +x local-php-security-checker
  - ./local-php-security-checker
  # QA check
  - composer qa-check
  # PHP unit tests
  - composer test-ci
  # SonarQube
  - sonar-scanner
