# Project language
language: php
sudo: false

# PHP version
php:
  - 7.2

# Cache composer packages so "composer install" is faster
cache:
  directories:
    - ${HOME}/.composer/cache/files

addons:
  sonarcloud:
    organization: "adshares-github"
    token:
      secure: "CrUof1+C1uYYH+3m4Je6tOyGge5qB8GPRNBH8T3doIrjLuXhs74ah+9qT9jgOwfDH9Rb6661oTIQVxuWjg5mJIDBnc8TnV0lROo4fVKYMc9F/YyPbYqYRz8Jyyup2s1xvgbGG43ho8tPY2tq7Dzwr0NUVYumWGOwdIejnSZkFGD6Hg6S1bkRq+MbUtXtLEcSjaH8wvhKDJNObK2xo3/v98XEE+kLLB4/R4QGaSCvZlQRgkZy+kMZ6ihnPKbR1faYDOe/rOZMmcsIMK0J32ujS2Y+ky/psYsrjIkZwXdIjObg8VCeBokfp/t9NpKuMPzffofG+eyHzvuo+V+M6Nt7blt2BrMsoBk8eQjv1UnYuPoiBnC3cQ09OMWeg6BQpwFMbU8XJSrvA9Qt2gMK/pkld7DsjV0ZOaBGrMpeU/JCD5Px6GAz14pIxAe/+Bz79Dvt/6y/RYvDtiP9x9Zn5PXrGCYbdILJ13mBnSI2oO9PI7osicaRL3dOaOSI/ID3+8jqu8wfB3Z4acnh06vttMNuTPF285PLJaFy2sGaxd+fUW4zYjWrOSoJbFnd6/2aQwBuk3Gu7/Vu5lGs132z3IB0IfqzHB/yDoHngNWezxdz0tJh/lZn1IoJ0ptXfJFuOy9buRACNEZ8YwA3L6d6QE8pBMcfq+ChdJk76w3jWO9mXsw="
    github_token:
      secure: "YaRbAgWUaf0G9XLBvIb7OaK8whXHPG/e+ZuST2H29Oip8F7NGxwaMvpORYqV6cEY85GB8Tv+Q/H5nA6TKrD/UdkfiIl95ieWAZheCJgr+1q/dYZDME+w3uhbm+BYF0buJ7asFJC+nvGqTrHGp5np99mI2LdDdCxyxcp1RZQaEGFyjgeEIfh/9QeQk8bRiFvowIJX6W8jxRU3VoZt1KQpALqwDKMpiyLKWMFQbhQPD9gDk1J+whuFks39DFo4tzyqWWxbzRHVYtUsx+0bzIOIivGqYsGNlpdYfIM1yP2E2bUtIOE17lhoy+SYJoupoFxzmaYr0TNc/e804BW5TdML1W30nqIQqzOXm3nlkgPPLMoGzPRZN5JejffrXh+FyoouwCWAGHg2rjAwJw9z/5SYY2ZOd6s8g/Ski8nCpGIKjgal+smONeA8YXeSj9vVF7j8mom4bDm+tqFmztrqFm9j5pKc293/5JvFnp/216gM2RMDoF6dM27UqGzPs4s1iS6k2DDOPM0rRdPs9nIkMngBhoIJDnjtcI3UkNFLoe+gu6tdAcSJg47Bb988M0usIcPENOPpzooPp7IRJBNJvPDO18H5W9rUBnsvHBQpOEiNY54xldPeri9OyMslmAdGfGdbCK+JyyS3qvYFpPhaApmbZnMvFKtIvQuecWz5wRwncgY="

# Install composer dependencies
install:
  - composer install --no-ansi --no-scripts --no-interaction --no-progress --no-suggest
  - composer run-script install-codestandards

script:
  # SensioLabs Security Checker: checks security issues
  - ./vendor/bin/security-checker security:check
  # PHP Lint: check syntax errors in all PHP files
  - ./vendor/bin/parallel-lint --no-colors --blame --exclude vendor .
  # PHP_CodeSniffer: check PHP compatibility
  - ./vendor/bin/phpcs -s --standard=PHPCompatibility src tests
  # PHP_CodeSniffer: check PSR2 standard
  - ./vendor/bin/phpcs -s --standard=PSR2 src tests
  # PHP Static Analysis Tool
  - ./vendor/bin/phpstan --no-ansi --no-progress analyse -c phpstan.neon -l 7 src tests
  # PHP unit tests
  - alias php='php -dzend_extension=xdebug.so'
  - alias phpunit='php ./vendor/bin/phpunit'
  - phpunit --testsuit Unit
  # SonarQube
  - sonar-scanner

# After a build, send email notification with the build results
notifications:
  email: false
  slack:
    rooms:
      secure: "bcZ/6zIfZ4D68+8Tdg4PEXy1nM4Yto+JNdcaYCTkTefpuBbu5hAoGtETpLbSZpg/xfONtOp8NDvxTKCjnsRR+DHHWbxYTszlZxgp0d8ir7TAwuCsqbOwJZFckfuN6OqORbBEfQpeFKujf1m39X+MFCECjGFgB5vujC3MiHrlsfT/bwgcBQ6ROhxX2d0oAtMsAW+GqQjKiwqoxr+eC3YPLh7r/+0XS7H6nFo/dJmrYpAupRVG/H3QgXOcIpYUR5RtB1YM+ZGQ20fQnrqgppFPJM2LRnDoGUrjd5N9LOg0QL+0LuydocH5iwKhPi5FGUq+6PH0IqmXCgNHKxbmPiPXhbT8EScSHJaLdUprmYZJ6Y47vrsJGP0mb3xmNKPnKveqOWF061hE7ugLYb5m4dOla+2IZzYjqBYQd8P55ENp4MR4NamJnbAJZQxhhNqGnVWf0lz83JBQUFxkbREqwj5ogNK/hpg4KH1ZJSPprZz34OzF5GOlvb10n1lRLSZm8Up2EFGh/L9mx0S0m6JL//rLoP+yi2Kdq6ZBKEzPu+PLRiAwYUyZ+oiWFAf9pNDcwbzKJZOe/u8GvA5Mye0QmrfCAnvTnUJNduNynn9Spg3omRZMreY8IuuQegz1N0xMu97YXkJuL8cUzFL9TlnJBWygIUFISP72JakBvM2o73KipDc="
    on_success: change
    on_failure: always
